"""Initial migration

Revision ID: 134e11e4c92a
Revises: 
Create Date: 2025-08-21 19:41:42.645121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '134e11e4c92a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_table('users')
    op.drop_table('dynamic_fields')
    op.drop_table('publications')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('name'))

    op.drop_table('departments')
    op.drop_table('form_fields')
    op.drop_table('commercializations')
    op.drop_table('users_new')
    with op.batch_alter_table('patents', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_constraint(batch_op.f('patents_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('filed_date')
        batch_op.drop_column('inventors')
        batch_op.drop_column('user_id')
        batch_op.drop_column('title')
        batch_op.drop_column('pname')
        batch_op.drop_column('grant_date')
        batch_op.drop_column('tech_transferred')
        batch_op.drop_column('PID')
        batch_op.drop_column('PID2')
        batch_op.drop_column('applicant')
        batch_op.drop_column('status')
        batch_op.drop_column('patent_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patent_number', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('status', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('applicant', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('PID2', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('PID', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tech_transferred', mysql.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('grant_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('pname', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('title', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('inventors', mysql.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('filed_date', sa.DATE(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('patents_ibfk_1'), 'users', ['user_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('phone',
               existing_type=sa.String(length=20),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=mysql.TEXT(),
               nullable=True)

    op.create_table('users_new',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('department_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('scholar_link', mysql.TEXT(), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('role', mysql.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('users_new_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('commercializations',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('project_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('cid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cno', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cname1', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('commercializations_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('form_fields',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('form_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('field_label', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('field_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('field_type', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('is_required', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('options', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('departments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    op.create_table('publications',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('title', mysql.TEXT(), nullable=True),
    sa.Column('authors', mysql.TEXT(), nullable=True),
    sa.Column('year', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('citations', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('publications_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('dynamic_fields',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('table_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('field_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('field_label', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('field_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('options', mysql.TEXT(), nullable=True),
    sa.Column('is_required', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('department_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('scholar_link', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('users_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
